StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5ED21314D4B73FC8}" {
   Id "ORS-Action_StartBuildingFob_Name"
   Target_en_us "START BUILDING FOB"
   Target_de_de "MIT DEM BAU EINES STÜTZPUNKTES STARTEN"
   Modified 1590832889
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED21307511F9180}" {
   Id "ORS-Briefing_Task_BuildFob_Description"
   Target_en_us "Build FOB in the objective areas"
   Target_de_de "Bauen Sie einen Stützpunkt in den Zielgebieten."
   Modified 1590840569
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED213002D392825}" {
   Id "ORS-Briefing_Task_Defend_Description"
   Target_en_us "Defend the FOBs"
   Target_de_de "Verteidigen Sie die Stützpunkte."
   Modified 1590840507
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED21304342E359B}" {
   Id "ORS-Briefing_Task_Seize_Description"
   Target_en_us "Seek and Destroy Targets in the objective areas."
   Target_de_de "Suchen und zerstören Sie Ziele in den Gebieten."
   Modified 1590840629
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED2131F0A00B846}" {
   Id "ORS-Scenario_Everon_Description"
   Target_en_us "Capture the island under FIA insurgents control. Insert, build your FOB, complete objectives and defend the FOB."
   Target_de_de "Erobere die Insel unter der Kontrolle von FIA Aufständischen. "
   Modified 1590832314
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED213148D62FDD9}" {
   Id "ORS-Scenario_Everon_US_Name"
   Target_en_us "[WIP] Operation Blue Eagle - Everon"
   Target_de_de "[WIP] Operation Blauer Adler - Everon"
   Modified 1590837812
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED21317FD75D080}" {
   Id "ORS-Scenario_Everon_USSR_Name"
   Target_en_us "[WIP] Operation Red Star - Everon"
   Target_de_de "[WIP] Operation Roter Stern - Everon"
   Modified 1590837815
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED213162A099D5E}" {
   Id "ORS-Task_BuildFob_Description"
   Target_en_us "Start building a FOB by creating a command post in the objective area."
   Target_de_de "Starten Sie mit dem Bau eines Stützpunktes indem Sie einen Kommandoposten im Gebiet bauen."
   Modified 1590832165
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED2131139FE97A0}" {
   Id "ORS-Task_BuildFob_Name"
   Target_en_us "Build FOB near %1"
   Target_de_de "Baue Stützpunkt in der Nähe von %1"
   Modified 1590837778
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED21311D8ED0E6F}" {
   Id "ORS-Task_Defend_Description"
   Target_en_us "The enemy is pereparing for a final counter attack. Do not let them retake the area!"
   Target_de_de "Der Feind bereitet eine letzte Gegenoffensive vor. Verlieren Sie auf keinen Fall das Gebiet!"
   Modified 1590831316
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED213025E4A7924}" {
   Id "ORS-Task_Destroy_Description"
   Target_en_us "Destroy the designated target."
   Target_de_de "Zerstören Sie das angegebene Ziel."
   Modified 1590837974
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED2130F0748AC9A}" {
   Id "ORS-Task_Destroy_Name"
   Target_en_us "Destroy %1"
   Target_de_de "Zerstöre %1"
   Modified 1590836134
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED21310EBB2BCE8}" {
   Id "ORS-Task_Seize_Description"
   Target_en_us "Seek and destroy targets and hold the area."
   Target_de_de "Suchen und zerstören Sie Ziele und halten Sie das Gebiet."
   Modified 1590837739
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5ED213039379AC5A}" {
   Id "ORS-Task_Seize_Name"
   Target_en_us "Seize %1"
   Target_de_de "Nehme %1 ein"
   Modified 1590838065
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}