SCR_MapConfig : "{19C76194B21EC3E1}Configs/Map/MapEditor.conf" {
 m_aUIComponents {
  ORS_MapUIElementContainer "{5584BECCCE38AB5B}" {
  }
  ORS_MapObjectiveAreaMarkersUI "{623CE977A5D714E8}" {
  }
  SCR_MapMarkersUI "{657606CF1D008A15}" {
  }
 }
}