SCR_MapConfig : "{1B8AC767E06A0ACD}Configs/Map/MapFullscreen.conf" {
 m_aUIComponents {
  SCR_MapUIElementContainer "{5510976DEBFC5555}" {
  }
  ORS_MapObjectiveAreaMarkersUI "{623CE977DB479CAE}" {
  }
 }
}