SCR_MapConfig : "{418989FA279F1257}Configs/Map/MapSpawnMenu.conf" {
 m_aUIComponents {
  ORS_MapUIElementContainer "{5CD4980FEBB71157}" {
  }
  ORS_MapObjectiveAreaMarkersUI "{623CE977D941D07D}" {
  }
 }
}