SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{6A234C81619351E1}" {
   Config "{E40D4AE2513E4145}Configs/Systems/Persistence/GameMode/ORS.conf"
  }
  ORS_EnemyReinforcementSystem "{6A234C850CA030FD}" {
  }
  ORS_EnemySupportSystem "{6A234C8500BC5ACB}" {
  }
 }
}