PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Databases {
  SaveGameDatabase "{6624ADA9A88DA0F6}" {
   SerializationSaveContext "SCR_PersistencePrettyJsonSaveContext"
   SerializationLoadContext "SCR_PersistenceJsonLoadContext"
   Bundler "JsonBundler"
  }
 }
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Setup {
     Configurations {
      EntityPersistenceConfig "{6A234C815AB2E23F}" {
       Rule EntityClassPersistenceConfigRule "{6A234C815CE844B7}" {
        EntityClass "ORS_ObjectiveArea"
       }
       Collection "{6586D01E488CA578}"
       EntitySerializer ORS_ObjectiveAreaSerializer "{6A234C814D8E28E2}" {
       }
      }
     }
    }
   }
  }
 }
}