PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Setup {
     Configurations {
      EntityPersistenceConfig "{6A234C815AB2E23F}" {
       Rule EntityClassPersistenceConfigRule "{6A234C815CE844B7}" {
        EntityClass "ORS_ObjectiveArea"
       }
       Collection "{6586D01E488CA578}"
       EntitySerializer ORS_ObjectiveAreaSerializer "{6A234C814D8E28E2}" {
       }
      }
     }
    }
    PersistenceConfigGroup Misc {
     Configurations {
      EntityPersistenceConfig "{69168A3B6C1CE43A}" {
       State Disabled
      }
     }
    }
   }
  }
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Gameplay {
     Configurations {
      StatePersistenceConfig "{6578ADCB37474BBC}" {
       State Disabled
      }
     }
    }
   }
  }
 }
 PersistentStates {
  SCR_TaskSystemData "{664E98561E79F319}" {
   Enabled 0
  }
 }
}