ORS_MissionHeader {
 World "{E4A854F3F75F8DD4}worlds/ORS/Eden/ORS_Eden.ent"
 SystemsConfig "{A5DF74EF8131C131}Configs/Systems/ORS_Systems.conf"
 m_sName "Operation Red Star - Everon (US vs USSR)"
 m_sAuthor "Kexanone"
 m_sDescription "Capture the island under USSR control. Insert, build your FOB, complete objectives and defend the FOB."
 m_sDetails "Capture the island under USSR control. Insert, build your FOB, complete objectives and defend the FOB."
 m_sIcon "{DE06FBCB3D1D9E6F}gfx/preview.edds"
 m_sLoadingScreen "{DE06FBCB3D1D9E6F}gfx/preview.edds"
 m_sPreviewImage "{DE06FBCB3D1D9E6F}gfx/preview.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 32
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_sPlayerFactionKey "US"
 m_sEnemyFactionKey "USSR"
}